// Decompiled with JetBrains decompiler
// Type: DetroitDiesel.ServiceRoutineTabs.Procedures.TCM_Clutch_Overload_Monitoring.panel.UserPanel
// Assembly: ServiceRoutineTabs, Version=8.19.5842.0, Culture=neutral, PublicKeyToken=1d4aea3187b835fe
// MVID: D5CFA739-5617-418F-8542-A6885771D80A
// Assembly location: C:\Users\petra\Downloads\Архив (2)\ServiceRoutineTabs.dll

using DetroitDiesel.Common;
using DetroitDiesel.Extensions.SharedProcedures;
using DetroitDiesel.Interfaces;
using DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments;
using SapiLayer1;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace DetroitDiesel.ServiceRoutineTabs.Procedures.TCM_Clutch_Overload_Monitoring.panel;

public class UserPanel : CustomPanel, IRefreshable
{
  private Channel tcm;
  private TableLayoutPanel tableLayoutPanel1;
  private DigitalReadoutInstrument digitalReadoutInstrument1;
  private DigitalReadoutInstrument digitalReadoutInstrument2;
  private DigitalReadoutInstrument digitalReadoutInstrument3;
  private DigitalReadoutInstrument digitalReadoutInstrument4;
  private DigitalReadoutInstrument digitalReadoutInstrument5;
  private DigitalReadoutInstrument digitalReadoutInstrument6;
  private DigitalReadoutInstrument digitalReadoutInstrument7;
  private DigitalReadoutInstrument digitalReadoutInstrument8;
  private DigitalReadoutInstrument digitalReadoutInstrument9;
  private DigitalReadoutInstrument digitalReadoutInstrument10;
  private DigitalReadoutInstrument digitalReadoutInstrument11;
  private DigitalReadoutInstrument digitalReadoutInstrument12;
  private DigitalReadoutInstrument digitalReadoutInstrument13;
  private DigitalReadoutInstrument digitalReadoutInstrument14;
  private DigitalReadoutInstrument digitalReadoutInstrument15;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage1;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage2;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage3;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage4;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage5;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage6;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage7;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage8;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage9;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage10;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage11;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage12;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage13;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage14;
  private DigitalReadoutInstrument digitalReadoutInstrumentMileage15;
  private BarInstrument barInstrument1;
  private BarInstrument barInstrument2;
  private BarInstrument barInstrument3;
  private BarInstrument barInstrument4;
  private BarInstrument barInstrument5;
  private BarInstrument barInstrument6;
  private BarInstrument barInstrument7;
  private BarInstrument barInstrument8;
  private BarInstrument barInstrument9;
  private BarInstrument barInstrument10;
  private BarInstrument barInstrument11;
  private BarInstrument barInstrument12;
  private BarInstrument barInstrument13;
  private BarInstrument barInstrument14;
  private BarInstrument barInstrument15;
  private DigitalReadoutInstrument digitalReadoutInstrument31;
  private DigitalReadoutInstrument digitalReadoutInstrument32;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label16;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label15;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label14;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label13;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label12;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label11;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label10;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label9;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label8;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label7;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label6;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label5;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label4;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label3;
  private DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label label1;
  private RunServiceButton runServiceButtonClear;
  private DigitalReadoutInstrument digitalReadoutInstrument33;

  public UserPanel()
  {
    this.InitializeComponent();
    this.runServiceButtonClear.ServiceComplete += new EventHandler<SingleServiceResultEventArgs>(this.OnServiceComplete);
  }

  public virtual void OnChannelsChanged() => this.UpdateChannel();

  private void UpdateChannel()
  {
    Channel channel = this.GetChannel("TCM01T", (CustomPanel.ChannelLookupOptions) 7);
    if (this.tcm == channel)
      return;
    this.tcm = channel;
    if (this.tcm != null)
    {
      foreach (SingleInstrumentBase singleInstrumentBase1 in CustomPanel.GetControlsOfType(((Control) this).Controls, typeof (SingleInstrumentBase)))
      {
        Qualifier instrument = singleInstrumentBase1.Instrument;
        Ecu ecuByName = SapiManager.GetEcuByName(((Qualifier) ref instrument).Ecu);
        if (ecuByName != null && ecuByName.Identifier == channel.Ecu.Identifier && ecuByName.Name != channel.Ecu.Name)
        {
          SingleInstrumentBase singleInstrumentBase2 = singleInstrumentBase1;
          instrument = singleInstrumentBase1.Instrument;
          QualifierTypes type = ((Qualifier) ref instrument).Type;
          string name1 = channel.Ecu.Name;
          instrument = singleInstrumentBase1.Instrument;
          string name2 = ((Qualifier) ref instrument).Name;
          Qualifier qualifier = new Qualifier(type, name1, name2);
          singleInstrumentBase2.Instrument = qualifier;
        }
      }
      if (this.tcm.Ecu.Name == "TCM01T")
        this.runServiceButtonClear.ServiceCall = new ServiceCall("TCM01T", "RT_0471_KupplungUeberdrueckt_Zaehler_zuruecksetzen_Start");
      else if (this.tcm.Ecu.Name == "TCM05T")
        this.runServiceButtonClear.ServiceCall = new ServiceCall("TCM05T", "RT_0471_Reset_clutch_overload_event_counter_Start");
    }
  }

  private void OnServiceComplete(object sender, SingleServiceResultEventArgs e)
  {
    if (((ResultEventArgs) e).Succeeded)
    {
      int num1 = (int) MessageBox.Show(e.Service.Name + Resources.Message_CompletedSuccessfully, ApplicationInformation.ProductName);
    }
    else
    {
      int num2 = (int) MessageBox.Show($"{e.Service.Name}{Resources.Message_Failed}{((ResultEventArgs) e).Exception.Message}'", ApplicationInformation.ProductName);
    }
  }

  public bool CanRefreshView
  {
    get
    {
      return SapiManager.GlobalInstance.Online && this.tcm != null && this.tcm.CommunicationsState == CommunicationsState.Online;
    }
  }

  public void RefreshView()
  {
    if (!SapiManager.GlobalInstance.Online || this.tcm == null || this.tcm.CommunicationsState != CommunicationsState.Online)
      return;
    this.tcm.EcuInfos.Read(false);
  }

  private void duration_DataChanged(object sender, EventArgs e)
  {
    this.UpdateVisibility(sender as SingleInstrumentBase);
  }

  private void temperature_DataChanged(object sender, EventArgs e)
  {
    this.UpdateVisibility(sender as SingleInstrumentBase);
  }

  private void UpdateVisibility(SingleInstrumentBase updatedInstrument)
  {
    if (updatedInstrument == null)
      return;
    int row = ((TableLayoutPanel) this.tableLayoutPanel1).GetRow((Control) updatedInstrument);
    SingleInstrumentBase controlFromPosition1 = (SingleInstrumentBase) ((TableLayoutPanel) this.tableLayoutPanel1).GetControlFromPosition(2, row);
    SingleInstrumentBase controlFromPosition2 = (SingleInstrumentBase) ((TableLayoutPanel) this.tableLayoutPanel1).GetControlFromPosition(3, row);
    if (controlFromPosition1.DataItem != null && controlFromPosition1.DataItem.Value != null && controlFromPosition2.DataItem != null && controlFromPosition2.DataItem.Value != null)
      ((TableLayoutPanel) this.tableLayoutPanel1).GetControlFromPosition(1, row).Visible = controlFromPosition1.DataItem.Value.ToString() != "s.n.a." || controlFromPosition2.DataItem.Value.ToString() != "s.n.a.";
  }

  private void InitializeComponent()
  {
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (UserPanel));
    this.tableLayoutPanel1 = new TableLayoutPanel();
    this.runServiceButtonClear = new RunServiceButton();
    this.label16 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label15 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label14 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label13 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label12 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label11 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label10 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label9 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label8 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label7 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label6 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label5 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label4 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.label3 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    this.digitalReadoutInstrument1 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument2 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument3 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument4 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument5 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument6 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument7 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument8 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument9 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument10 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument11 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument12 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument13 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument14 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument15 = new DigitalReadoutInstrument();
    this.barInstrument1 = new BarInstrument();
    this.barInstrument2 = new BarInstrument();
    this.barInstrument3 = new BarInstrument();
    this.barInstrument4 = new BarInstrument();
    this.barInstrument5 = new BarInstrument();
    this.barInstrument6 = new BarInstrument();
    this.barInstrument7 = new BarInstrument();
    this.barInstrument8 = new BarInstrument();
    this.barInstrument9 = new BarInstrument();
    this.barInstrument10 = new BarInstrument();
    this.barInstrument11 = new BarInstrument();
    this.barInstrument12 = new BarInstrument();
    this.barInstrument13 = new BarInstrument();
    this.barInstrument14 = new BarInstrument();
    this.barInstrument15 = new BarInstrument();
    this.digitalReadoutInstrument31 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument33 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument32 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage1 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage2 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage3 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage4 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage5 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage6 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage7 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage8 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage9 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage10 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage11 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage12 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage13 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage14 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrumentMileage15 = new DigitalReadoutInstrument();
    this.label1 = new DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label();
    ((Control) this.tableLayoutPanel1).SuspendLayout();
    ((Control) this).SuspendLayout();
    componentResourceManager.ApplyResources((object) this.tableLayoutPanel1, "tableLayoutPanel1");
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.runServiceButtonClear, 4, 16 /*0x10*/);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label16, 0, 15);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label15, 0, 14);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label14, 0, 13);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label13, 0, 12);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label12, 0, 11);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label11, 0, 10);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label10, 0, 9);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label9, 0, 8);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label8, 0, 7);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label7, 0, 6);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label6, 0, 5);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label5, 0, 4);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label4, 0, 3);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label3, 0, 2);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument1, 2, 1);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument2, 2, 2);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument3, 2, 3);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument4, 2, 4);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument5, 2, 5);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument6, 2, 6);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument7, 2, 7);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument8, 2, 8);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument9, 2, 9);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument10, 2, 10);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument11, 2, 11);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument12, 2, 12);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument13, 2, 13);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument14, 2, 14);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument15, 2, 15);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument1, 3, 1);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument2, 3, 2);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument3, 3, 3);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument4, 3, 4);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument5, 3, 5);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument6, 3, 6);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument7, 3, 7);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument8, 3, 8);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument9, 3, 9);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument10, 3, 10);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument11, 3, 11);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument12, 3, 12);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument13, 3, 13);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument14, 3, 14);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument15, 3, 15);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument31, 2, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument33, 3, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument32, 1, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage1, 1, 1);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage2, 1, 2);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage3, 1, 3);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage4, 1, 4);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage5, 1, 5);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage6, 1, 6);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage7, 1, 7);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage8, 1, 8);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage9, 1, 9);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage10, 1, 10);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage11, 1, 11);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage12, 1, 12);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage13, 1, 13);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage14, 1, 14);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrumentMileage15, 1, 15);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.label1, 0, 1);
    ((Control) this.tableLayoutPanel1).Name = "tableLayoutPanel1";
    componentResourceManager.ApplyResources((object) this.runServiceButtonClear, "runServiceButtonClear");
    ((Control) this.runServiceButtonClear).Name = "runServiceButtonClear";
    this.runServiceButtonClear.ServiceCall = new ServiceCall("TCM01T", "RT_0471_KupplungUeberdrueckt_Zaehler_zuruecksetzen_Start");
    this.label16.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label16, "label16");
    ((Control) this.label16).Name = "label16";
    this.label16.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label16.ShowBorder = false;
    this.label16.UseSystemColors = true;
    this.label15.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label15, "label15");
    ((Control) this.label15).Name = "label15";
    this.label15.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label15.ShowBorder = false;
    this.label15.UseSystemColors = true;
    this.label14.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label14, "label14");
    ((Control) this.label14).Name = "label14";
    this.label14.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label14.ShowBorder = false;
    this.label14.UseSystemColors = true;
    this.label13.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label13, "label13");
    ((Control) this.label13).Name = "label13";
    this.label13.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label13.ShowBorder = false;
    this.label13.UseSystemColors = true;
    this.label12.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label12, "label12");
    ((Control) this.label12).Name = "label12";
    this.label12.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label12.ShowBorder = false;
    this.label12.UseSystemColors = true;
    this.label11.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label11, "label11");
    ((Control) this.label11).Name = "label11";
    this.label11.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label11.ShowBorder = false;
    this.label11.UseSystemColors = true;
    this.label10.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label10, "label10");
    ((Control) this.label10).Name = "label10";
    this.label10.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label10.ShowBorder = false;
    this.label10.UseSystemColors = true;
    this.label9.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label9, "label9");
    ((Control) this.label9).Name = "label9";
    this.label9.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label9.ShowBorder = false;
    this.label9.UseSystemColors = true;
    this.label8.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label8, "label8");
    ((Control) this.label8).Name = "label8";
    this.label8.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label8.ShowBorder = false;
    this.label8.UseSystemColors = true;
    this.label7.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label7, "label7");
    ((Control) this.label7).Name = "label7";
    this.label7.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label7.ShowBorder = false;
    this.label7.UseSystemColors = true;
    this.label6.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label6, "label6");
    ((Control) this.label6).Name = "label6";
    this.label6.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label6.ShowBorder = false;
    this.label6.UseSystemColors = true;
    this.label5.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label5, "label5");
    ((Control) this.label5).Name = "label5";
    this.label5.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label5.ShowBorder = false;
    this.label5.UseSystemColors = true;
    this.label4.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label4, "label4");
    ((Control) this.label4).Name = "label4";
    this.label4.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label4.ShowBorder = false;
    this.label4.UseSystemColors = true;
    this.label3.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label3, "label3");
    ((Control) this.label3).Name = "label3";
    this.label3.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label3.ShowBorder = false;
    this.label3.UseSystemColors = true;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument1, "digitalReadoutInstrument1");
    this.digitalReadoutInstrument1.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument1).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument1).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2611_clutch_overload_monitoring_ring_buffer_event_1_duration");
    ((Control) this.digitalReadoutInstrument1).Name = "digitalReadoutInstrument1";
    ((SingleInstrumentBase) this.digitalReadoutInstrument1).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument1).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument1).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument2, "digitalReadoutInstrument2");
    this.digitalReadoutInstrument2.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument2).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument2).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2612_clutch_overload_monitoring_ring_buffer_event_2_duration");
    ((Control) this.digitalReadoutInstrument2).Name = "digitalReadoutInstrument2";
    ((SingleInstrumentBase) this.digitalReadoutInstrument2).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument2).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument2).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument3, "digitalReadoutInstrument3");
    this.digitalReadoutInstrument3.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2613_clutch_overload_monitoring_ring_buffer_event_3_duration");
    ((Control) this.digitalReadoutInstrument3).Name = "digitalReadoutInstrument3";
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument4, "digitalReadoutInstrument4");
    this.digitalReadoutInstrument4.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2614_clutch_overload_monitoring_ring_buffer_event_4_duration");
    ((Control) this.digitalReadoutInstrument4).Name = "digitalReadoutInstrument4";
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument5, "digitalReadoutInstrument5");
    this.digitalReadoutInstrument5.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2615_clutch_overload_monitoring_ring_buffer_event_5_duration");
    ((Control) this.digitalReadoutInstrument5).Name = "digitalReadoutInstrument5";
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument6, "digitalReadoutInstrument6");
    this.digitalReadoutInstrument6.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2616_clutch_overload_monitoring_ring_buffer_event_6_duration");
    ((Control) this.digitalReadoutInstrument6).Name = "digitalReadoutInstrument6";
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument7, "digitalReadoutInstrument7");
    this.digitalReadoutInstrument7.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2617_clutch_overload_monitoring_ring_buffer_event_7_duration");
    ((Control) this.digitalReadoutInstrument7).Name = "digitalReadoutInstrument7";
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument8, "digitalReadoutInstrument8");
    this.digitalReadoutInstrument8.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2618_clutch_overload_monitoring_ring_buffer_event_8_duration");
    ((Control) this.digitalReadoutInstrument8).Name = "digitalReadoutInstrument8";
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument9, "digitalReadoutInstrument9");
    this.digitalReadoutInstrument9.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2619_clutch_overload_monitoring_ring_buffer_event_9_duration");
    ((Control) this.digitalReadoutInstrument9).Name = "digitalReadoutInstrument9";
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument10, "digitalReadoutInstrument10");
    this.digitalReadoutInstrument10.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261A_clutch_overload_monitoring_ring_buffer_event_10_duration");
    ((Control) this.digitalReadoutInstrument10).Name = "digitalReadoutInstrument10";
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument11, "digitalReadoutInstrument11");
    this.digitalReadoutInstrument11.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261B_clutch_overload_monitoring_ring_buffer_event_11_duration");
    ((Control) this.digitalReadoutInstrument11).Name = "digitalReadoutInstrument11";
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument12, "digitalReadoutInstrument12");
    this.digitalReadoutInstrument12.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261C_clutch_overload_monitoring_ring_buffer_event_12_duration");
    ((Control) this.digitalReadoutInstrument12).Name = "digitalReadoutInstrument12";
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument13, "digitalReadoutInstrument13");
    this.digitalReadoutInstrument13.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261D_clutch_overload_monitoring_ring_buffer_event_13_duration");
    ((Control) this.digitalReadoutInstrument13).Name = "digitalReadoutInstrument13";
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument14, "digitalReadoutInstrument14");
    this.digitalReadoutInstrument14.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument14).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument14).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261E_clutch_overload_monitoring_ring_buffer_event_14_duration");
    ((Control) this.digitalReadoutInstrument14).Name = "digitalReadoutInstrument14";
    ((SingleInstrumentBase) this.digitalReadoutInstrument14).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument14).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument14).DataChanged += new EventHandler(this.duration_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument15, "digitalReadoutInstrument15");
    this.digitalReadoutInstrument15.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrument15).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument15).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261F_clutch_overload_monitoring_ring_buffer_event_15_duration");
    ((Control) this.digitalReadoutInstrument15).Name = "digitalReadoutInstrument15";
    ((SingleInstrumentBase) this.digitalReadoutInstrument15).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrument15).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.digitalReadoutInstrument15).DataChanged += new EventHandler(this.duration_DataChanged);
    this.barInstrument1.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument1, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument1, "barInstrument1");
    this.barInstrument1.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument1).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument1).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2611_clutch_overload_monitoring_ring_buffer_event_1_peak_temperature");
    ((Control) this.barInstrument1).Name = "barInstrument1";
    ((AxisSingleInstrumentBase) this.barInstrument1).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument1).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument1).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument1).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument2.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument2, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument2, "barInstrument2");
    this.barInstrument2.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument2).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument2).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2612_clutch_overload_monitoring_ring_buffer_event_2_peak_temperature");
    ((Control) this.barInstrument2).Name = "barInstrument2";
    ((AxisSingleInstrumentBase) this.barInstrument2).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument2).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument2).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument2).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument3.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument3, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument3, "barInstrument3");
    this.barInstrument3.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument3).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument3).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2613_clutch_overload_monitoring_ring_buffer_event_3_peak_temperature");
    ((Control) this.barInstrument3).Name = "barInstrument3";
    ((AxisSingleInstrumentBase) this.barInstrument3).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument3).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument3).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument3).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument4.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument4, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument4, "barInstrument4");
    this.barInstrument4.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument4).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument4).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2614_clutch_overload_monitoring_ring_buffer_event_4_peak_temperature");
    ((Control) this.barInstrument4).Name = "barInstrument4";
    ((AxisSingleInstrumentBase) this.barInstrument4).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument4).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument4).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument4).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument5.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument5, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument5, "barInstrument5");
    this.barInstrument5.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument5).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument5).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2615_clutch_overload_monitoring_ring_buffer_event_5_peak_temperature");
    ((Control) this.barInstrument5).Name = "barInstrument5";
    ((AxisSingleInstrumentBase) this.barInstrument5).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument5).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument5).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument5).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument6.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument6, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument6, "barInstrument6");
    this.barInstrument6.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument6).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument6).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2616_clutch_overload_monitoring_ring_buffer_event_6_peak_temperature");
    ((Control) this.barInstrument6).Name = "barInstrument6";
    ((AxisSingleInstrumentBase) this.barInstrument6).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument6).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument6).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument6).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument7.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument7, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument7, "barInstrument7");
    this.barInstrument7.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument7).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument7).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2617_clutch_overload_monitoring_ring_buffer_event_7_peak_temperature");
    ((Control) this.barInstrument7).Name = "barInstrument7";
    ((AxisSingleInstrumentBase) this.barInstrument7).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument7).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument7).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument7).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument8.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument8, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument8, "barInstrument8");
    this.barInstrument8.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument8).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument8).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2618_clutch_overload_monitoring_ring_buffer_event_8_peak_temperature");
    ((Control) this.barInstrument8).Name = "barInstrument8";
    ((AxisSingleInstrumentBase) this.barInstrument8).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument8).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument8).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument8).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument9.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument9, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument9, "barInstrument9");
    this.barInstrument9.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument9).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument9).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2619_clutch_overload_monitoring_ring_buffer_event_9_peak_temperature");
    ((Control) this.barInstrument9).Name = "barInstrument9";
    ((AxisSingleInstrumentBase) this.barInstrument9).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument9).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument9).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument9).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument10.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument10, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument10, "barInstrument10");
    this.barInstrument10.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument10).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument10).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261A_clutch_overload_monitoring_ring_buffer_event_10_peak_temperature");
    ((Control) this.barInstrument10).Name = "barInstrument10";
    ((AxisSingleInstrumentBase) this.barInstrument10).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument10).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument10).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument10).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument11.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument11, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument11, "barInstrument11");
    this.barInstrument11.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument11).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument11).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261B_clutch_overload_monitoring_ring_buffer_event_11_peak_temperature");
    ((Control) this.barInstrument11).Name = "barInstrument11";
    ((AxisSingleInstrumentBase) this.barInstrument11).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument11).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument11).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument11).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument12.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument12, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument12, "barInstrument12");
    this.barInstrument12.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument12).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument12).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261C_clutch_overload_monitoring_ring_buffer_event_12_peak_temperature");
    ((Control) this.barInstrument12).Name = "barInstrument12";
    ((AxisSingleInstrumentBase) this.barInstrument12).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument12).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument12).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument12).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument13.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument13, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument13, "barInstrument13");
    this.barInstrument13.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument13).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument13).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261D_clutch_overload_monitoring_ring_buffer_event_13_peak_temperature");
    ((Control) this.barInstrument13).Name = "barInstrument13";
    ((AxisSingleInstrumentBase) this.barInstrument13).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument13).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument13).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument13).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument14.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument14, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument14, "barInstrument14");
    this.barInstrument14.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument14).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument14).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261E_clutch_overload_monitoring_ring_buffer_event_14_peak_temperature");
    ((Control) this.barInstrument14).Name = "barInstrument14";
    ((AxisSingleInstrumentBase) this.barInstrument14).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument14).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument14).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument14).DataChanged += new EventHandler(this.temperature_DataChanged);
    this.barInstrument15.BarStyle = (BarControl.ControlStyle) 1;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.barInstrument15, 2);
    componentResourceManager.ApplyResources((object) this.barInstrument15, "barInstrument15");
    this.barInstrument15.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.barInstrument15).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument15).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261F_clutch_overload_monitoring_ring_buffer_event_15_peak_temperature");
    ((Control) this.barInstrument15).Name = "barInstrument15";
    ((AxisSingleInstrumentBase) this.barInstrument15).PreferredAxisRange = new AxisRange(-100.0, 500.0, "°C");
    ((SingleInstrumentBase) this.barInstrument15).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.barInstrument15).UnitAlignment = StringAlignment.Near;
    ((SingleInstrumentBase) this.barInstrument15).DataChanged += new EventHandler(this.temperature_DataChanged);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument31, "digitalReadoutInstrument31");
    this.digitalReadoutInstrument31.FontGroup = (string) null;
    ((SingleInstrumentBase) this.digitalReadoutInstrument31).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument31).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2611_clutch_overload_monitoring_ring_buffer_event_1_duration");
    ((Control) this.digitalReadoutInstrument31).Name = "digitalReadoutInstrument31";
    ((SingleInstrumentBase) this.digitalReadoutInstrument31).TitleLengthPercentOfControl = 100;
    ((SingleInstrumentBase) this.digitalReadoutInstrument31).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.digitalReadoutInstrument31).UnitAlignment = StringAlignment.Near;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.digitalReadoutInstrument33, 2);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument33, "digitalReadoutInstrument33");
    this.digitalReadoutInstrument33.FontGroup = (string) null;
    ((SingleInstrumentBase) this.digitalReadoutInstrument33).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument33).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2611_clutch_overload_monitoring_ring_buffer_event_1_peak_temperature");
    ((Control) this.digitalReadoutInstrument33).Name = "digitalReadoutInstrument33";
    ((SingleInstrumentBase) this.digitalReadoutInstrument33).TitleLengthPercentOfControl = 100;
    ((SingleInstrumentBase) this.digitalReadoutInstrument33).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.digitalReadoutInstrument33).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument32, "digitalReadoutInstrument32");
    this.digitalReadoutInstrument32.FontGroup = (string) null;
    ((SingleInstrumentBase) this.digitalReadoutInstrument32).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument32).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2611_clutch_overload_monitoring_ring_buffer_event_1_milage");
    ((Control) this.digitalReadoutInstrument32).Name = "digitalReadoutInstrument32";
    ((SingleInstrumentBase) this.digitalReadoutInstrument32).TitleLengthPercentOfControl = 100;
    ((SingleInstrumentBase) this.digitalReadoutInstrument32).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.digitalReadoutInstrument32).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage1, "digitalReadoutInstrumentMileage1");
    this.digitalReadoutInstrumentMileage1.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage1).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage1).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2611_clutch_overload_monitoring_ring_buffer_event_1_milage");
    ((Control) this.digitalReadoutInstrumentMileage1).Name = "digitalReadoutInstrumentMileage1";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage1).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage1).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage2, "digitalReadoutInstrumentMileage2");
    this.digitalReadoutInstrumentMileage2.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage2).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage2).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2612_clutch_overload_monitoring_ring_buffer_event_2_milage");
    ((Control) this.digitalReadoutInstrumentMileage2).Name = "digitalReadoutInstrumentMileage2";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage2).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage2).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage3, "digitalReadoutInstrumentMileage3");
    this.digitalReadoutInstrumentMileage3.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage3).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage3).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2613_clutch_overload_monitoring_ring_buffer_event_3_milage");
    ((Control) this.digitalReadoutInstrumentMileage3).Name = "digitalReadoutInstrumentMileage3";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage3).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage3).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage4, "digitalReadoutInstrumentMileage4");
    this.digitalReadoutInstrumentMileage4.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage4).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage4).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2614_clutch_overload_monitoring_ring_buffer_event_4_milage");
    ((Control) this.digitalReadoutInstrumentMileage4).Name = "digitalReadoutInstrumentMileage4";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage4).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage4).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage5, "digitalReadoutInstrumentMileage5");
    this.digitalReadoutInstrumentMileage5.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage5).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage5).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2615_clutch_overload_monitoring_ring_buffer_event_5_milage");
    ((Control) this.digitalReadoutInstrumentMileage5).Name = "digitalReadoutInstrumentMileage5";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage5).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage5).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage6, "digitalReadoutInstrumentMileage6");
    this.digitalReadoutInstrumentMileage6.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage6).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage6).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2616_clutch_overload_monitoring_ring_buffer_event_6_milage");
    ((Control) this.digitalReadoutInstrumentMileage6).Name = "digitalReadoutInstrumentMileage6";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage6).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage6).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage7, "digitalReadoutInstrumentMileage7");
    this.digitalReadoutInstrumentMileage7.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage7).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage7).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2617_clutch_overload_monitoring_ring_buffer_event_7_milage");
    ((Control) this.digitalReadoutInstrumentMileage7).Name = "digitalReadoutInstrumentMileage7";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage7).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage7).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage8, "digitalReadoutInstrumentMileage8");
    this.digitalReadoutInstrumentMileage8.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage8).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage8).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2618_clutch_overload_monitoring_ring_buffer_event_8_milage");
    ((Control) this.digitalReadoutInstrumentMileage8).Name = "digitalReadoutInstrumentMileage8";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage8).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage8).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage9, "digitalReadoutInstrumentMileage9");
    this.digitalReadoutInstrumentMileage9.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage9).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage9).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_2619_clutch_overload_monitoring_ring_buffer_event_9_milage");
    ((Control) this.digitalReadoutInstrumentMileage9).Name = "digitalReadoutInstrumentMileage9";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage9).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage9).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage10, "digitalReadoutInstrumentMileage10");
    this.digitalReadoutInstrumentMileage10.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage10).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage10).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261A_clutch_overload_monitoring_ring_buffer_event_10_milage");
    ((Control) this.digitalReadoutInstrumentMileage10).Name = "digitalReadoutInstrumentMileage10";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage10).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage10).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage11, "digitalReadoutInstrumentMileage11");
    this.digitalReadoutInstrumentMileage11.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage11).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage11).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261B_clutch_overload_monitoring_ring_buffer_event_11_milage");
    ((Control) this.digitalReadoutInstrumentMileage11).Name = "digitalReadoutInstrumentMileage11";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage11).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage11).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage12, "digitalReadoutInstrumentMileage12");
    this.digitalReadoutInstrumentMileage12.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage12).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage12).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261C_clutch_overload_monitoring_ring_buffer_event_12_milage");
    ((Control) this.digitalReadoutInstrumentMileage12).Name = "digitalReadoutInstrumentMileage12";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage12).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage12).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage13, "digitalReadoutInstrumentMileage13");
    this.digitalReadoutInstrumentMileage13.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage13).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage13).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261D_clutch_overload_monitoring_ring_buffer_event_13_milage");
    ((Control) this.digitalReadoutInstrumentMileage13).Name = "digitalReadoutInstrumentMileage13";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage13).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage13).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage14, "digitalReadoutInstrumentMileage14");
    this.digitalReadoutInstrumentMileage14.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage14).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage14).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261E_clutch_overload_monitoring_ring_buffer_event_14_milage");
    ((Control) this.digitalReadoutInstrumentMileage14).Name = "digitalReadoutInstrumentMileage14";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage14).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage14).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrumentMileage15, "digitalReadoutInstrumentMileage15");
    this.digitalReadoutInstrumentMileage15.FontGroup = "TCM_clutch_data";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage15).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage15).Instrument = new Qualifier((QualifierTypes) 8, "TCM01T", "DT_261F_clutch_overload_monitoring_ring_buffer_event_15_milage");
    ((Control) this.digitalReadoutInstrumentMileage15).Name = "digitalReadoutInstrumentMileage15";
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage15).TitlePosition = (LabelPosition) 0;
    ((SingleInstrumentBase) this.digitalReadoutInstrumentMileage15).UnitAlignment = StringAlignment.Near;
    this.label1.Alignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.label1, "label1");
    ((Control) this.label1).Name = "label1";
    this.label1.Orientation = (DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments.Label.TextOrientation) 1;
    this.label1.ShowBorder = false;
    this.label1.UseSystemColors = true;
    componentResourceManager.ApplyResources((object) this, "$this");
    ((Control) this).Controls.Add((Control) this.tableLayoutPanel1);
    ((Control) this).Name = nameof (UserPanel);
    ((Control) this.tableLayoutPanel1).ResumeLayout(false);
    ((Control) this.tableLayoutPanel1).PerformLayout();
    ((Control) this).ResumeLayout(false);
  }
}
