using System.ComponentModel;

namespace DetroitDiesel.ServiceRoutineTabs.Dialogs.Set_CPC_Odometer__EPA07_.panel;

public class Resources
{
	private static ComponentResourceManager ResourceManager => new ComponentResourceManager(typeof(UserPanel));

	internal static string Message_TheOdometerCannotBeSetBecauseTheProposedValueIsEffectivelyEqualToCurrentOdometer => ResourceManager.GetString("StringTable.Message_TheOdometerCannotBeSetBecauseTheProposedValueIsEffectivelyEqualToCurrentOdometer");

	internal static string MessageFormat_AnErrorOccurredSettingTheOdometer => ResourceManager.GetString("StringTable.MessageFormat_AnErrorOccurredSettingTheOdometer");

	internal static string Message_ErrorTheOdometerCannotBeSetBecauseTheProposedValueIsLessThanTheCurrentOdometer => ResourceManager.GetString("StringTable.Message_ErrorTheOdometerCannotBeSetBecauseTheProposedValueIsLessThanTheCurrentOdometer");

	internal static string Message_TheOdometerIsReadyToBeSetBecauseTheProposedValueIsGreaterThanTheCurrentOdometer => ResourceManager.GetString("StringTable.Message_TheOdometerIsReadyToBeSetBecauseTheProposedValueIsGreaterThanTheCurrentOdometer");

	internal static string Message_TheOdometerValueIsUnknownAndCannotBeSet => ResourceManager.GetString("StringTable.Message_TheOdometerValueIsUnknownAndCannotBeSet");

	internal static string Message_TheOdometerHasBeenSetTheValueShownMayBeSlightlyDifferentThanTheOneEnteredDueToRoundingIssues => ResourceManager.GetString("StringTable.Message_TheOdometerHasBeenSetTheValueShownMayBeSlightlyDifferentThanTheOneEnteredDueToRoundingIssues");
}
