namespace McdAbstraction;

internal enum E_PDU_ERR_EVT
{
	PDU_ERR_EVT_NOERROR = 0,
	PDU_ERR_EVT_FRAME_STRUCT = 256,
	PDU_ERR_EVT_TX_ERROR = 257,
	PDU_ERR_EVT_TESTER_PRESENT_ERROR = 258,
	PDU_ERR_EVT_RSC_LOCKED = 265,
	PDU_ERR_EVT_RX_TIMEOUT = 259,
	PDU_ERR_EVT_RX_ERROR = 260,
	PDU_ERR_EVT_PROT_ERR = 261,
	PDU_ERR_EVT_LOST_COMM_TO_VCI = 262,
	PDU_ERR_EVT_VCI_HARDWARE_FAULT = 263,
	PDU_ERR_EVT_INIT_ERROR = 264
}
