using System.ComponentModel;

namespace DetroitDiesel.ServiceRoutineTabs.Dialogs.Predictive_Cruise_Control_diagnostic__MY13_.panel;

public class Resources
{
	private static ComponentResourceManager ResourceManager => new ComponentResourceManager(typeof(UserPanel));

	internal static string Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedWhenTheCPCIsOnlineAndInAnApplicationMode => ResourceManager.GetString("StringTable.Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedWhenTheCPCIsOnlineAndInAnApplicationMode");

	internal static string Message_ThePredictiveCruiseControlDeviceIsDetectedOnTheDataLinkAndTheCPCAppearsToBeConfiguredToUseIt => ResourceManager.GetString("StringTable.Message_ThePredictiveCruiseControlDeviceIsDetectedOnTheDataLinkAndTheCPCAppearsToBeConfiguredToUseIt");

	internal static string Message_TheCPCIsNotConfiguredForPredictiveCruiseControlOperationAndTheDeviceIsNotDetectedOnTheDataLink => ResourceManager.GetString("StringTable.Message_TheCPCIsNotConfiguredForPredictiveCruiseControlOperationAndTheDeviceIsNotDetectedOnTheDataLink");

	internal static string Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedOnceParametersHaveBeenReadFromTheCPCPleaseWait => ResourceManager.GetString("StringTable.Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedOnceParametersHaveBeenReadFromTheCPCPleaseWait");

	internal static string Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedWhenTheDiagnosticToolIsConnectedToAJ1939Vehicle => ResourceManager.GetString("StringTable.Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedWhenTheDiagnosticToolIsConnectedToAJ1939Vehicle");

	internal static string Message_TheCPCIsConfiguredForPredictiveCruiseControlOperationButTheDeviceIsNotDetectedOnTheDataLinkCheckTheVehicleWiring => ResourceManager.GetString("StringTable.Message_TheCPCIsConfiguredForPredictiveCruiseControlOperationButTheDeviceIsNotDetectedOnTheDataLinkCheckTheVehicleWiring");

	internal static string Message_NoDataLink => ResourceManager.GetString("StringTable.Message_NoDataLink");

	internal static string Message_ThePredictiveCruiseControlDeviceIsDetectedOnTheDataLinkButTheCPCIsNotConfiguredToUseItUseTheDropDownToChangeTheCPCConfigurationThenPressTheSendButtonToCommit => ResourceManager.GetString("StringTable.Message_ThePredictiveCruiseControlDeviceIsDetectedOnTheDataLinkButTheCPCIsNotConfiguredToUseItUseTheDropDownToChangeTheCPCConfigurationThenPressTheSendButtonToCommit");

	internal static string Message_ThePredictiveCruiseControlConfigurationIsBeingWrittenToTheCPCPleaseWait => ResourceManager.GetString("StringTable.Message_ThePredictiveCruiseControlConfigurationIsBeingWrittenToTheCPCPleaseWait");

	internal static string Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedWhenAutomaticConnectionToStandardSAEJ1939DevicesIsEnabledInToolsOptionsConnections => ResourceManager.GetString("StringTable.Message_ThePredictiveCruiseControlConfigurationCanOnlyBeValidatedWhenAutomaticConnectionToStandardSAEJ1939DevicesIsEnabledInToolsOptionsConnections");

	internal static string Message_UnableToDetect => ResourceManager.GetString("StringTable.Message_UnableToDetect");

	internal static string Message_NotDetected => ResourceManager.GetString("StringTable.Message_NotDetected");

	internal static string Message_Detected0 => ResourceManager.GetString("StringTable.Message_Detected0");
}
