using System.ComponentModel;

namespace DetroitDiesel.ServiceRoutineTabs.Dialogs.Detroit_Assurance_Global_Radar_Dyno_Mode.panel;

public class Resources
{
	private static ComponentResourceManager ResourceManager => new ComponentResourceManager(typeof(UserPanel));

	internal static string Message_TheDetroitAssuranceAdvancedBrakeAssistFunctionIsCurrentlyDisabledToEnableDetroitAssuranceOnThisVehicleClickTheStartButton => ResourceManager.GetString("StringTable.Message_TheDetroitAssuranceAdvancedBrakeAssistFunctionIsCurrentlyDisabledToEnableDetroitAssuranceOnThisVehicleClickTheStartButton");

	internal static string Message_TheDetroitAssuranceAdvancedBrakeAssistFunctionIsCurrentlyEnabledToDisableDetroitAssuranceOnThisVehicleClickTheStartButton => ResourceManager.GetString("StringTable.Message_TheDetroitAssuranceAdvancedBrakeAssistFunctionIsCurrentlyEnabledToDisableDetroitAssuranceOnThisVehicleClickTheStartButton");
}
