namespace Softing.Dts;

public enum DtsBusSystemInterfaceType : uint
{
	eBUSSYSTEMINTERFACE_UNDEF = 7424u,
	eBUSSYSTEMINTERFACE_PDUAPI,
	eBUSSYSTEMINTERFACE_VECOM,
	eBUSSYSTEMINTERFACE_DAG,
	eBUSSYSTEMINTERFACE_SIMULATION,
	eBUSSYSTEMINTERFACE_INCA
}
