namespace Softing.Dts;

public enum DtsComPrimitiveType : uint
{
	START_BUS_COMMUNICATION = 32513u,
	STOP_BUS_COMMUNICATION,
	GOTO_ONLINE,
	GOTO_OFFLINE,
	VARIANT_IDENTIFICATION,
	VARIANT_IDENTIFICATION_AND_SELECTION,
	HEX_SERVICE,
	RAW_SERVICE,
	PROTOCOL_PARAMETER_SET,
	_DELAY,
	SERVICE,
	SINGLE_ECU_JOB,
	MULTIPLE_ECU_JOB,
	SET_VARIANT,
	SYSTEM_COMPRIMITIVE,
	DYNID_DEFINE_COMPRIMITIVE,
	DYNID_READ_COMPRIMITIVE,
	FLASH_JOB,
	DYNID_CLEAR_COMPRIMITIVE
}
