namespace Softing.Dts;

public enum DtsDiagCodedLengthType : uint
{
	eMCDUNDEFLENGTHTYPE = 29184u,
	eMCDSTANDARDLENGTHTYPE,
	eMCDMINMAXLENGTHTYPE,
	eMCDLEADINGLENGTHINFOTYPE,
	eMCDPARAMLENGTHINFOTYPE
}
