namespace Softing.Dts;

public enum DtsEventType : uint
{
	ePRIMITIVE_EVENT = 6912u,
	eLINK_EVENT,
	eSYSTEM_EVENT,
	eCONFIGURATION_RECORD_EVENT,
	eINTERFACE_EVENT,
	eMONITORING_EVENT,
	eSTATIC_INTERFACE_EVENT
}
