// Decompiled with JetBrains decompiler
// Type: DetroitDiesel.ServiceRoutineTabs.Procedures.Soot_Sensor__MY20_.panel.UserPanel
// Assembly: ServiceRoutineTabs, Version=8.19.5842.0, Culture=neutral, PublicKeyToken=1d4aea3187b835fe
// MVID: D5CFA739-5617-418F-8542-A6885771D80A
// Assembly location: C:\Users\petra\Downloads\Архив (2)\ServiceRoutineTabs.dll

using DetroitDiesel.Common;
using DetroitDiesel.Extensions.SharedProcedures;
using DetroitDiesel.Help;
using DetroitDiesel.Utilities;
using DetroitDiesel.Windows.Forms.Diagnostics.Panels.Instruments;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace DetroitDiesel.ServiceRoutineTabs.Procedures.Soot_Sensor__MY20_.panel;

public class UserPanel : CustomPanel
{
  private DigitalReadoutInstrument DigitalReadoutInstrument2;
  private TableLayoutPanel tableLayoutPanel1;
  private SharedProcedureIntegrationComponent sharedProcedureIntegrationComponent1;
  private Checkmark checkmarkStatus;
  private DigitalReadoutInstrument digitalReadoutInstrument5;
  private DigitalReadoutInstrument digitalReadoutInstrument9;
  private DigitalReadoutInstrument digitalReadoutInstrument13;
  private DigitalReadoutInstrument digitalReadoutInstrument4;
  private DigitalReadoutInstrument digitalReadoutInstrument3;
  private SeekTimeListView seekTimeListView;
  private TableLayoutPanel tableStatusIndicators;
  private Label labelStatus;
  private Button buttonStart;
  private BarInstrument BarInstrument11;
  private BarInstrument BarInstrument10;
  private BarInstrument BarInstrument9;
  private BarInstrument barInstrument14;
  private BarInstrument BarInstrument13;
  private DigitalReadoutInstrument digitalReadoutInstrument7;
  private DigitalReadoutInstrument digitalReadoutInstrument6;
  private DigitalReadoutInstrument digitalReadoutInstrument8;
  private DigitalReadoutInstrument digitalReadoutInstrument10;
  private DigitalReadoutInstrument digitalReadoutInstrument11;
  private SharedProcedureSelection sharedProcedureSelection1;
  private DigitalReadoutInstrument digitalReadoutInstrument12;
  private DigitalReadoutInstrument DigitalReadoutInstrument1;

  public UserPanel() => this.InitializeComponent();

  private void InitializeComponent()
  {
    this.components = (IContainer) new Container();
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (UserPanel));
    this.tableStatusIndicators = new TableLayoutPanel();
    this.sharedProcedureSelection1 = new SharedProcedureSelection();
    this.buttonStart = new Button();
    this.labelStatus = new Label();
    this.checkmarkStatus = new Checkmark();
    this.tableLayoutPanel1 = new TableLayoutPanel();
    this.digitalReadoutInstrument12 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument11 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument10 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument8 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument6 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument7 = new DigitalReadoutInstrument();
    this.seekTimeListView = new SeekTimeListView();
    this.digitalReadoutInstrument4 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument3 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument5 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument9 = new DigitalReadoutInstrument();
    this.digitalReadoutInstrument13 = new DigitalReadoutInstrument();
    this.DigitalReadoutInstrument1 = new DigitalReadoutInstrument();
    this.BarInstrument11 = new BarInstrument();
    this.BarInstrument10 = new BarInstrument();
    this.BarInstrument9 = new BarInstrument();
    this.barInstrument14 = new BarInstrument();
    this.BarInstrument13 = new BarInstrument();
    this.DigitalReadoutInstrument2 = new DigitalReadoutInstrument();
    this.sharedProcedureIntegrationComponent1 = new SharedProcedureIntegrationComponent(this.components);
    ((Control) this.tableStatusIndicators).SuspendLayout();
    ((Control) this.tableLayoutPanel1).SuspendLayout();
    ((Control) this).SuspendLayout();
    componentResourceManager.ApplyResources((object) this.tableStatusIndicators, "tableStatusIndicators");
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.tableStatusIndicators, 7);
    ((TableLayoutPanel) this.tableStatusIndicators).Controls.Add((Control) this.sharedProcedureSelection1, 3, 0);
    ((TableLayoutPanel) this.tableStatusIndicators).Controls.Add((Control) this.buttonStart, 0, 0);
    ((TableLayoutPanel) this.tableStatusIndicators).Controls.Add((Control) this.labelStatus, 2, 0);
    ((TableLayoutPanel) this.tableStatusIndicators).Controls.Add((Control) this.checkmarkStatus, 1, 0);
    ((Control) this.tableStatusIndicators).Name = "tableStatusIndicators";
    componentResourceManager.ApplyResources((object) this.sharedProcedureSelection1, "sharedProcedureSelection1");
    ((Control) this.sharedProcedureSelection1).Name = "sharedProcedureSelection1";
    this.sharedProcedureSelection1.SharedProcedureQualifiers = new SubjectCollection((IEnumerable<string>) new string[1]
    {
      "SP_PMSensorInspection_MY20"
    });
    ((Control) this.sharedProcedureSelection1).TabStop = false;
    componentResourceManager.ApplyResources((object) this.buttonStart, "buttonStart");
    this.buttonStart.Name = "buttonStart";
    this.buttonStart.UseCompatibleTextRendering = true;
    this.buttonStart.UseVisualStyleBackColor = true;
    componentResourceManager.ApplyResources((object) this.labelStatus, "labelStatus");
    this.labelStatus.Name = "labelStatus";
    this.labelStatus.UseCompatibleTextRendering = true;
    this.checkmarkStatus.CheckState = CheckState.Checked;
    componentResourceManager.ApplyResources((object) this.checkmarkStatus, "checkmarkStatus");
    ((Control) this.checkmarkStatus).Name = "checkmarkStatus";
    componentResourceManager.ApplyResources((object) this.tableLayoutPanel1, "tableLayoutPanel1");
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument12, 1, 5);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument11, 0, 4);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument10, 1, 3);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument8, 1, 1);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument6, 1, 7);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument7, 0, 6);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.seekTimeListView, 2, 4);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument4, 1, 2);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument3, 0, 2);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument5, 0, 5);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument9, 0, 3);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.digitalReadoutInstrument13, 0, 7);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.DigitalReadoutInstrument1, 0, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.BarInstrument11, 4, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.BarInstrument10, 5, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.BarInstrument9, 6, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.barInstrument14, 2, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.BarInstrument13, 3, 0);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.DigitalReadoutInstrument2, 0, 1);
    ((TableLayoutPanel) this.tableLayoutPanel1).Controls.Add((Control) this.tableStatusIndicators, 0, 8);
    ((Control) this.tableLayoutPanel1).Name = "tableLayoutPanel1";
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument12, "digitalReadoutInstrument12");
    this.digitalReadoutInstrument12.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).FreezeValue = false;
    this.digitalReadoutInstrument12.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText"));
    this.digitalReadoutInstrument12.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText1"));
    this.digitalReadoutInstrument12.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText2"));
    this.digitalReadoutInstrument12.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText3"));
    this.digitalReadoutInstrument12.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText4"));
    this.digitalReadoutInstrument12.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText5"));
    this.digitalReadoutInstrument12.Gradient.Initialize((ValueState) 0, 5);
    this.digitalReadoutInstrument12.Gradient.Modify(1, 0.0, (ValueState) 2);
    this.digitalReadoutInstrument12.Gradient.Modify(2, 1.0, (ValueState) 1);
    this.digitalReadoutInstrument12.Gradient.Modify(3, 2.0, (ValueState) 3);
    this.digitalReadoutInstrument12.Gradient.Modify(4, 3.0, (ValueState) 3);
    this.digitalReadoutInstrument12.Gradient.Modify(5, (double) byte.MaxValue, (ValueState) 3);
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).Instrument = new Qualifier((QualifierTypes) 64 /*0x40*/, "ACM301T", "RT_SR0D3_PM_Sensor_inspection_Request_Results_End_of_DSR_shutdown_in_case_of_cooled_down_sensor");
    ((Control) this.digitalReadoutInstrument12).Name = "digitalReadoutInstrument12";
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument12).UnitAlignment = StringAlignment.Near;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.digitalReadoutInstrument11, 2);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument11, "digitalReadoutInstrument11");
    this.digitalReadoutInstrument11.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).FreezeValue = false;
    this.digitalReadoutInstrument11.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText6"));
    this.digitalReadoutInstrument11.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText7"));
    this.digitalReadoutInstrument11.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText8"));
    this.digitalReadoutInstrument11.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText9"));
    this.digitalReadoutInstrument11.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText10"));
    this.digitalReadoutInstrument11.Gradient.Initialize((ValueState) 0, 4);
    this.digitalReadoutInstrument11.Gradient.Modify(1, 0.0, (ValueState) 0);
    this.digitalReadoutInstrument11.Gradient.Modify(2, 1.0, (ValueState) 1);
    this.digitalReadoutInstrument11.Gradient.Modify(3, 2.0, (ValueState) 0);
    this.digitalReadoutInstrument11.Gradient.Modify(4, 3.0, (ValueState) 0);
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS106_NOx_Sensor_Dewpoint_enabled_Outlet");
    ((Control) this.digitalReadoutInstrument11).Name = "digitalReadoutInstrument11";
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument11).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument10, "digitalReadoutInstrument10");
    this.digitalReadoutInstrument10.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).FreezeValue = false;
    this.digitalReadoutInstrument10.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText11"));
    this.digitalReadoutInstrument10.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText12"));
    this.digitalReadoutInstrument10.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText13"));
    this.digitalReadoutInstrument10.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText14"));
    this.digitalReadoutInstrument10.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText15"));
    this.digitalReadoutInstrument10.Gradient.Initialize((ValueState) 0, 4);
    this.digitalReadoutInstrument10.Gradient.Modify(1, 0.0, (ValueState) 0);
    this.digitalReadoutInstrument10.Gradient.Modify(2, 1.0, (ValueState) 0);
    this.digitalReadoutInstrument10.Gradient.Modify(3, 2.0, (ValueState) 0);
    this.digitalReadoutInstrument10.Gradient.Modify(4, 3.0, (ValueState) 0);
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_DS013_Soot_Sensor_Data_Prot_tube_monitoring_release");
    ((Control) this.digitalReadoutInstrument10).Name = "digitalReadoutInstrument10";
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument10).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument8, "digitalReadoutInstrument8");
    this.digitalReadoutInstrument8.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).FreezeValue = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS195_isp_dps_cid");
    ((Control) this.digitalReadoutInstrument8).Name = "digitalReadoutInstrument8";
    ((SingleInstrumentBase) this.digitalReadoutInstrument8).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument6, "digitalReadoutInstrument6");
    this.digitalReadoutInstrument6.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).FreezeValue = false;
    this.digitalReadoutInstrument6.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText16"));
    this.digitalReadoutInstrument6.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText17"));
    this.digitalReadoutInstrument6.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText18"));
    this.digitalReadoutInstrument6.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText19"));
    this.digitalReadoutInstrument6.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText20"));
    this.digitalReadoutInstrument6.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText21"));
    this.digitalReadoutInstrument6.Gradient.Initialize((ValueState) 0, 5);
    this.digitalReadoutInstrument6.Gradient.Modify(1, 0.0, (ValueState) 1);
    this.digitalReadoutInstrument6.Gradient.Modify(2, 1.0, (ValueState) 3);
    this.digitalReadoutInstrument6.Gradient.Modify(3, 2.0, (ValueState) 3);
    this.digitalReadoutInstrument6.Gradient.Modify(4, 3.0, (ValueState) 3);
    this.digitalReadoutInstrument6.Gradient.Modify(5, (double) byte.MaxValue, (ValueState) 0);
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).Instrument = new Qualifier((QualifierTypes) 64 /*0x40*/, "ACM301T", "RT_SR0D3_PM_Sensor_inspection_Request_Results_DPS_short_circuit_failure_value");
    ((Control) this.digitalReadoutInstrument6).Name = "digitalReadoutInstrument6";
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument6).UnitAlignment = StringAlignment.Near;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.digitalReadoutInstrument7, 2);
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument7, "digitalReadoutInstrument7");
    this.digitalReadoutInstrument7.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).FreezeValue = false;
    this.digitalReadoutInstrument7.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText22"));
    this.digitalReadoutInstrument7.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText23"));
    this.digitalReadoutInstrument7.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText24"));
    this.digitalReadoutInstrument7.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText25"));
    this.digitalReadoutInstrument7.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText26"));
    this.digitalReadoutInstrument7.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText27"));
    this.digitalReadoutInstrument7.Gradient.Initialize((ValueState) 0, 5);
    this.digitalReadoutInstrument7.Gradient.Modify(1, 0.0, (ValueState) 0);
    this.digitalReadoutInstrument7.Gradient.Modify(2, 1.0, (ValueState) 1);
    this.digitalReadoutInstrument7.Gradient.Modify(3, 2.0, (ValueState) 3);
    this.digitalReadoutInstrument7.Gradient.Modify(4, 3.0, (ValueState) 3);
    this.digitalReadoutInstrument7.Gradient.Modify(5, (double) byte.MaxValue, (ValueState) 3);
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).Instrument = new Qualifier((QualifierTypes) 64 /*0x40*/, "ACM301T", "RT_SR0D3_PM_Sensor_inspection_Request_Results_Measurement_active_value");
    ((Control) this.digitalReadoutInstrument7).Name = "digitalReadoutInstrument7";
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument7).UnitAlignment = StringAlignment.Near;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.seekTimeListView, 5);
    componentResourceManager.ApplyResources((object) this.seekTimeListView, "seekTimeListView");
    this.seekTimeListView.FilterUserLabels = true;
    ((Control) this.seekTimeListView).Name = "seekTimeListView";
    this.seekTimeListView.RequiredUserLabelPrefix = "PMSensorInspection";
    ((TableLayoutPanel) this.tableLayoutPanel1).SetRowSpan((Control) this.seekTimeListView, 4);
    this.seekTimeListView.SelectedTime = new DateTime?();
    this.seekTimeListView.ShowChannelLabels = false;
    this.seekTimeListView.ShowCommunicationsState = false;
    this.seekTimeListView.ShowControlPanel = false;
    this.seekTimeListView.ShowDeviceColumn = false;
    this.seekTimeListView.TimeFormat = "HH:mm:ss.fff";
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument4, "digitalReadoutInstrument4");
    this.digitalReadoutInstrument4.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).FreezeValue = false;
    this.digitalReadoutInstrument4.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText28"));
    this.digitalReadoutInstrument4.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText29"));
    this.digitalReadoutInstrument4.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText30"));
    this.digitalReadoutInstrument4.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText31"));
    this.digitalReadoutInstrument4.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText32"));
    this.digitalReadoutInstrument4.Gradient.Initialize((ValueState) 0, 4);
    this.digitalReadoutInstrument4.Gradient.Modify(1, 0.0, (ValueState) 0);
    this.digitalReadoutInstrument4.Gradient.Modify(2, 1.0, (ValueState) 0);
    this.digitalReadoutInstrument4.Gradient.Modify(3, 2.0, (ValueState) 0);
    this.digitalReadoutInstrument4.Gradient.Modify(4, 3.0, (ValueState) 0);
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_DS012_PM_sensor_active_status");
    ((Control) this.digitalReadoutInstrument4).Name = "digitalReadoutInstrument4";
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument4).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument3, "digitalReadoutInstrument3");
    this.digitalReadoutInstrument3.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).FreezeValue = false;
    this.digitalReadoutInstrument3.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText33"));
    this.digitalReadoutInstrument3.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText34"));
    this.digitalReadoutInstrument3.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText35"));
    this.digitalReadoutInstrument3.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText36"));
    this.digitalReadoutInstrument3.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText37"));
    this.digitalReadoutInstrument3.Gradient.Initialize((ValueState) 0, 4);
    this.digitalReadoutInstrument3.Gradient.Modify(1, 0.0, (ValueState) 0);
    this.digitalReadoutInstrument3.Gradient.Modify(2, 1.0, (ValueState) 0);
    this.digitalReadoutInstrument3.Gradient.Modify(3, 2.0, (ValueState) 0);
    this.digitalReadoutInstrument3.Gradient.Modify(4, 3.0, (ValueState) 0);
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_DS012_PM_sensor_regen_status");
    ((Control) this.digitalReadoutInstrument3).Name = "digitalReadoutInstrument3";
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument3).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument5, "digitalReadoutInstrument5");
    this.digitalReadoutInstrument5.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).FreezeValue = false;
    this.digitalReadoutInstrument5.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText38"));
    this.digitalReadoutInstrument5.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText39"));
    this.digitalReadoutInstrument5.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText40"));
    this.digitalReadoutInstrument5.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText41"));
    this.digitalReadoutInstrument5.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText42"));
    this.digitalReadoutInstrument5.Gradient.Initialize((ValueState) 0, 4);
    this.digitalReadoutInstrument5.Gradient.Modify(1, 0.0, (ValueState) 0);
    this.digitalReadoutInstrument5.Gradient.Modify(2, 1.0, (ValueState) 1);
    this.digitalReadoutInstrument5.Gradient.Modify(3, 2.0, (ValueState) 0);
    this.digitalReadoutInstrument5.Gradient.Modify(4, 3.0, (ValueState) 0);
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_DS014_Soot_Sensor_Data_regeneration_cycle_finished");
    ((Control) this.digitalReadoutInstrument5).Name = "digitalReadoutInstrument5";
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument5).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument9, "digitalReadoutInstrument9");
    this.digitalReadoutInstrument9.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).FreezeValue = false;
    this.digitalReadoutInstrument9.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText43"));
    this.digitalReadoutInstrument9.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText44"));
    this.digitalReadoutInstrument9.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText45"));
    this.digitalReadoutInstrument9.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText46"));
    this.digitalReadoutInstrument9.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText47"));
    this.digitalReadoutInstrument9.Gradient.Initialize((ValueState) 0, 4);
    this.digitalReadoutInstrument9.Gradient.Modify(1, 0.0, (ValueState) 0);
    this.digitalReadoutInstrument9.Gradient.Modify(2, 1.0, (ValueState) 0);
    this.digitalReadoutInstrument9.Gradient.Modify(3, 2.0, (ValueState) 0);
    this.digitalReadoutInstrument9.Gradient.Modify(4, 3.0, (ValueState) 0);
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_DS013_Soot_Sensor_Data_Regeneration_active");
    ((Control) this.digitalReadoutInstrument9).Name = "digitalReadoutInstrument9";
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument9).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.digitalReadoutInstrument13, "digitalReadoutInstrument13");
    this.digitalReadoutInstrument13.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).FreezeValue = false;
    this.digitalReadoutInstrument13.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText48"));
    this.digitalReadoutInstrument13.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText49"));
    this.digitalReadoutInstrument13.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText50"));
    this.digitalReadoutInstrument13.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText51"));
    this.digitalReadoutInstrument13.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText52"));
    this.digitalReadoutInstrument13.Gradient.DisplayText.Add(componentResourceManager.GetString("resource.DisplayText53"));
    this.digitalReadoutInstrument13.Gradient.Initialize((ValueState) 0, 5);
    this.digitalReadoutInstrument13.Gradient.Modify(1, 0.0, (ValueState) 1);
    this.digitalReadoutInstrument13.Gradient.Modify(2, 1.0, (ValueState) 3);
    this.digitalReadoutInstrument13.Gradient.Modify(3, 2.0, (ValueState) 3);
    this.digitalReadoutInstrument13.Gradient.Modify(4, 3.0, (ValueState) 3);
    this.digitalReadoutInstrument13.Gradient.Modify(5, (double) byte.MaxValue, (ValueState) 3);
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).Instrument = new Qualifier((QualifierTypes) 64 /*0x40*/, "ACM301T", "RT_SR0D3_PM_Sensor_inspection_Request_Results_DPS_sum_failure");
    ((Control) this.digitalReadoutInstrument13).Name = "digitalReadoutInstrument13";
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).ShowValueReadout = false;
    ((SingleInstrumentBase) this.digitalReadoutInstrument13).UnitAlignment = StringAlignment.Near;
    ((TableLayoutPanel) this.tableLayoutPanel1).SetColumnSpan((Control) this.DigitalReadoutInstrument1, 2);
    componentResourceManager.ApplyResources((object) this.DigitalReadoutInstrument1, "DigitalReadoutInstrument1");
    this.DigitalReadoutInstrument1.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.DigitalReadoutInstrument1).FreezeValue = false;
    ((SingleInstrumentBase) this.DigitalReadoutInstrument1).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS189_absolute_current_of_PM_sensor");
    ((Control) this.DigitalReadoutInstrument1).Name = "DigitalReadoutInstrument1";
    ((SingleInstrumentBase) this.DigitalReadoutInstrument1).UnitAlignment = StringAlignment.Near;
    this.BarInstrument11.BarOrientation = (BarControl.ControlOrientation) 1;
    this.BarInstrument11.BarStyle = (BarControl.ControlStyle) 1;
    componentResourceManager.ApplyResources((object) this.BarInstrument11, "BarInstrument11");
    this.BarInstrument11.FontGroup = "SootSensor_Thermometers";
    ((SingleInstrumentBase) this.BarInstrument11).FreezeValue = false;
    ((SingleInstrumentBase) this.BarInstrument11).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS019_SCR_Outlet_Temperature");
    ((Control) this.BarInstrument11).Name = "BarInstrument11";
    ((AxisSingleInstrumentBase) this.BarInstrument11).PreferredAxisRange = new AxisRange(-17.0, 1025.0, "");
    ((TableLayoutPanel) this.tableLayoutPanel1).SetRowSpan((Control) this.BarInstrument11, 4);
    ((SingleInstrumentBase) this.BarInstrument11).TitleOrientation = (Label.TextOrientation) 0;
    ((SingleInstrumentBase) this.BarInstrument11).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.BarInstrument11).UnitAlignment = StringAlignment.Near;
    this.BarInstrument10.BarOrientation = (BarControl.ControlOrientation) 1;
    this.BarInstrument10.BarStyle = (BarControl.ControlStyle) 1;
    componentResourceManager.ApplyResources((object) this.BarInstrument10, "BarInstrument10");
    this.BarInstrument10.FontGroup = "SootSensor_Thermometers";
    ((SingleInstrumentBase) this.BarInstrument10).FreezeValue = false;
    ((SingleInstrumentBase) this.BarInstrument10).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS190_measured_temp_at_PM_sensor");
    ((Control) this.BarInstrument10).Name = "BarInstrument10";
    ((AxisSingleInstrumentBase) this.BarInstrument10).PreferredAxisRange = new AxisRange(-17.0, 1025.0, "");
    ((TableLayoutPanel) this.tableLayoutPanel1).SetRowSpan((Control) this.BarInstrument10, 4);
    ((SingleInstrumentBase) this.BarInstrument10).TitleOrientation = (Label.TextOrientation) 0;
    ((SingleInstrumentBase) this.BarInstrument10).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.BarInstrument10).UnitAlignment = StringAlignment.Near;
    this.BarInstrument9.BarOrientation = (BarControl.ControlOrientation) 1;
    this.BarInstrument9.BarStyle = (BarControl.ControlStyle) 1;
    componentResourceManager.ApplyResources((object) this.BarInstrument9, "BarInstrument9");
    this.BarInstrument9.FontGroup = "SootSensor_Thermometers";
    ((SingleInstrumentBase) this.BarInstrument9).FreezeValue = false;
    ((SingleInstrumentBase) this.BarInstrument9).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS194_isp_dps_t_mea_iv");
    ((Control) this.BarInstrument9).Name = "BarInstrument9";
    ((AxisSingleInstrumentBase) this.BarInstrument9).PreferredAxisRange = new AxisRange(-17.0, 1025.0, "");
    ((TableLayoutPanel) this.tableLayoutPanel1).SetRowSpan((Control) this.BarInstrument9, 4);
    ((SingleInstrumentBase) this.BarInstrument9).TitleOrientation = (Label.TextOrientation) 0;
    ((SingleInstrumentBase) this.BarInstrument9).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.BarInstrument9).UnitAlignment = StringAlignment.Near;
    this.barInstrument14.BarOrientation = (BarControl.ControlOrientation) 1;
    this.barInstrument14.BarStyle = (BarControl.ControlStyle) 1;
    componentResourceManager.ApplyResources((object) this.barInstrument14, "barInstrument14");
    this.barInstrument14.FontGroup = "SootSensor_Thermometers";
    ((SingleInstrumentBase) this.barInstrument14).FreezeValue = false;
    ((SingleInstrumentBase) this.barInstrument14).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS053_Ambient_Air_Temperature");
    ((Control) this.barInstrument14).Name = "barInstrument14";
    ((AxisSingleInstrumentBase) this.barInstrument14).PreferredAxisRange = new AxisRange(-20.0, 80.0, "");
    ((TableLayoutPanel) this.tableLayoutPanel1).SetRowSpan((Control) this.barInstrument14, 4);
    ((SingleInstrumentBase) this.barInstrument14).TitleOrientation = (Label.TextOrientation) 0;
    ((SingleInstrumentBase) this.barInstrument14).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.barInstrument14).UnitAlignment = StringAlignment.Near;
    this.BarInstrument13.BarOrientation = (BarControl.ControlOrientation) 1;
    this.BarInstrument13.BarStyle = (BarControl.ControlStyle) 1;
    componentResourceManager.ApplyResources((object) this.BarInstrument13, "BarInstrument13");
    this.BarInstrument13.FontGroup = "SootSensor_Thermometers";
    ((SingleInstrumentBase) this.BarInstrument13).FreezeValue = false;
    ((SingleInstrumentBase) this.BarInstrument13).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS009_DPF_Outlet_Temperature");
    ((Control) this.BarInstrument13).Name = "BarInstrument13";
    ((AxisSingleInstrumentBase) this.BarInstrument13).PreferredAxisRange = new AxisRange(-17.0, 1025.0, "");
    ((TableLayoutPanel) this.tableLayoutPanel1).SetRowSpan((Control) this.BarInstrument13, 4);
    ((SingleInstrumentBase) this.BarInstrument13).TitleOrientation = (Label.TextOrientation) 0;
    ((SingleInstrumentBase) this.BarInstrument13).TitlePosition = (LabelPosition) 3;
    ((SingleInstrumentBase) this.BarInstrument13).UnitAlignment = StringAlignment.Near;
    componentResourceManager.ApplyResources((object) this.DigitalReadoutInstrument2, "DigitalReadoutInstrument2");
    this.DigitalReadoutInstrument2.FontGroup = "Soot Sensor Readouts";
    ((SingleInstrumentBase) this.DigitalReadoutInstrument2).FreezeValue = false;
    ((SingleInstrumentBase) this.DigitalReadoutInstrument2).Instrument = new Qualifier((QualifierTypes) 1, "ACM301T", "DT_AS191_PM_sensor_PWM_control");
    ((Control) this.DigitalReadoutInstrument2).Name = "DigitalReadoutInstrument2";
    ((SingleInstrumentBase) this.DigitalReadoutInstrument2).UnitAlignment = StringAlignment.Near;
    this.sharedProcedureIntegrationComponent1.ProceduresDropDown = this.sharedProcedureSelection1;
    this.sharedProcedureIntegrationComponent1.ProcedureStatusMessageTarget = this.labelStatus;
    this.sharedProcedureIntegrationComponent1.ProcedureStatusStateTarget = this.checkmarkStatus;
    this.sharedProcedureIntegrationComponent1.ResultsTarget = (TextBoxBase) null;
    this.sharedProcedureIntegrationComponent1.StartStopButton = this.buttonStart;
    this.sharedProcedureIntegrationComponent1.StopAllButton = (Button) null;
    componentResourceManager.ApplyResources((object) this, "$this");
    this.ContextLink = new Link("Panel_Soot_Sensor");
    ((Control) this).Controls.Add((Control) this.tableLayoutPanel1);
    ((Control) this).Name = nameof (UserPanel);
    ((Control) this.tableStatusIndicators).ResumeLayout(false);
    ((Control) this.tableStatusIndicators).PerformLayout();
    ((Control) this.tableLayoutPanel1).ResumeLayout(false);
    ((Control) this).ResumeLayout(false);
  }
}
